[profile.release-with-debug]
inherits = "release"
debug = true
split-debuginfo = "packed"

[workspace]
members = ["example", "interface", "svm/cli", "svm/executor"]

[workspace.package]
version = "0.1.0"
authors = ["Soon Labs <maintainers@soon.foundation>"]
repository = "https://github.com/soonlabs/soon"
homepage = "https://www.soo.network/"
license = "Apache-2.0"
edition = "2021"

[workspace.dependencies]
thiserror = "1.0.56"
bincode = "1.3.3"
env_logger = "0.11.0"
log = "0.4.20"
anyhow = "1.0.79"
hex = "0.4.3"
clap = "4.5"
tokio = "1.37"
chrono = "0.4.24"
rand = "0.8.5"

solana-bpf-loader-program = { git = "https://github.com/anza-xyz/agave.git", rev = "57a09f19f989228f1cfb195203cc60ea0120dd08" }
solana-compute-budget = { git = "https://github.com/anza-xyz/agave.git", rev = "57a09f19f989228f1cfb195203cc60ea0120dd08" }
solana-program-runtime = { git = "https://github.com/anza-xyz/agave.git", rev = "57a09f19f989228f1cfb195203cc60ea0120dd08" }
solana-sdk = { git = "https://github.com/anza-xyz/agave.git", rev = "57a09f19f989228f1cfb195203cc60ea0120dd08" }
solana-svm = { git = "https://github.com/anza-xyz/agave.git", rev = "57a09f19f989228f1cfb195203cc60ea0120dd08" }
solana-system-program = { git = "https://github.com/anza-xyz/agave.git", rev = "57a09f19f989228f1cfb195203cc60ea0120dd08" }
solana-logger = { git = "https://github.com/anza-xyz/agave.git", rev = "57a09f19f989228f1cfb195203cc60ea0120dd08" }
solana-test-validator = { git = "https://github.com/anza-xyz/agave.git", rev = "57a09f19f989228f1cfb195203cc60ea0120dd08" }
solana-ledger = { git = "https://github.com/anza-xyz/agave.git", rev = "57a09f19f989228f1cfb195203cc60ea0120dd08" }
solana-runtime = { git = "https://github.com/anza-xyz/agave.git", rev = "57a09f19f989228f1cfb195203cc60ea0120dd08" }

rollups-interface = { path = "interface" }
svm-executor = { path = "svm/executor" }

[patch.crates-io]
crossbeam-epoch = { git = "https://github.com/anza-xyz/crossbeam", rev = "fd279d707025f0e60951e429bf778b4813d1b6bf" }
solana-curve25519 = { git = "https://github.com/anza-xyz/agave.git", rev = "57a09f19f989228f1cfb195203cc60ea0120dd08" }
solana-program = { git = "https://github.com/anza-xyz/agave.git", rev = "57a09f19f989228f1cfb195203cc60ea0120dd08" }
solana-zk-sdk = { git = "https://github.com/anza-xyz/agave.git", rev = "57a09f19f989228f1cfb195203cc60ea0120dd08" }
solana-zk-token-sdk = { git = "https://github.com/anza-xyz/agave.git", rev = "57a09f19f989228f1cfb195203cc60ea0120dd08" }
